
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: blog_development
  username: harshit111 
  password: harshit123
  host: localhost


test:
  <<: *default
  adapter: postgresql
  database: blog_test
  username: harshit111 
  password: harshit123
  host: localhost



production:
  <<: *default
  adapter: postgresql
  database: blog_production
  username: harshit111 
  password: harshit123
  host: localhost
